# Generated by Django 3.2.9 on 2021-12-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('telephone_number', models.CharField(max_length=30)),
                ('extra_telephone_number', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('New', 'New'), ('Loyal', 'Loyal')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('telephone_number', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.PositiveSmallIntegerField()),
                ('course_days', models.CharField(choices=[('Monday-Friday', 'Monday-Friday'), ('Monday-Wednesday-Friday', 'Monday-Wednesday-Friday'), ('Tuesday-Thursday-Saturday', 'Tuesday-Thursday-Saturday'), ('Monday-Saturday', 'Monday-Saturday')], max_length=100)),
                ('course_time', models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00')], max_length=30)),
                ('group_name', models.CharField(max_length=30)),
                ('contract_maker', models.CharField(max_length=30)),
                ('first_lesson_day', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'active'), ('Passive', 'Passive')], max_length=15)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.courses')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CRM.teacher')),
            ],
        ),
    ]
