# Generated by Django 3.2.9 on 2021-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
